### ISSUE TITLE
Broken! Jsdom has changed.

### ISSUE THREAD

**Issue by derekrazo** [fallanic/scrape2csv#1]
Hi!

This code is broken as jsdom has changed in the recentish past. 

Don't know if you wanna update it but just thought I should let you know.

@ahdinosaur

**Comment by fallanic** [comment]
Thanks for letting me know!

I'll look into it when I find some time.

**Comment by fallanic** [comment]
This should now be fixed, thanks again for pointing that out @derekrazo
